version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch
   # image: elasticsearch:7.17.20
    image: mirror.gcr.io/elasticsearch:7.17.20
    restart: unless-stopped
    volumes:
      - /media/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "test"
      discovery.type: single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
#    image: kibana:7.17.20
    image: mirror.gcr.io/kibana:7.17.20
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elk
    volumes:
      - /media/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
networks:
  elk:
    driver: bridge
