---

- name: Deploy docker, elasticsearch, kibana
  remote_user: andy
  become: true
  become_user: root
  hosts: ELK
  gather_facts: true
  roles:
    - role: docker_install
    - role: elastic_kibana_install
#      tags: start el_ki
      vars:
        elk_container: docker_kibana_elastic
        el_config: elasticsearch
        el_config_dir: elastic
        ki_config: kibana
        ki_config_dir: kibana
