---
- name: Zabbix Server Install
  remote_user: andy
  become: true
  become_user: root
  hosts: ZabbixSRV
  gather_facts: false
  tasks:
    - name: Install packages
      become: yes
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-pip
          - python3-dev
          - python3-venv
          - python3-psycopg2
        state: present

    - name: Create database PostgreSQL 4 Zabbix
      become: yes
      become_user: postgres
      #become_user: root
      vars:
        student_database: zabbix
        student_user: zabbix
        student_password: ZabbixPasswd01
        password_for_default_postgres_user: qazwsxedc
      block:
        - postgresql_user:
            name: postgres
            password: '{{ password_for_default_postgres_user }}'
        - postgresql_db:
            db: '{{ student_database }}'
            encoding: UTF-8
            state: present
        - postgresql_user:
            db: '{{ student_database }}'
            name: '{{ student_user }}'
            password: '{{ student_password }}'
            state: present
            expires: infinity
            priv: CREATE,CONNECT,TEMPORARY
        - postgresql_db:
            db: '{{ student_database }}'
            owner: '{{ student_user }}'
            encoding: UTF-8
            state: present
        - postgresql_privs:
            database: '{{ student_database }}'
            state: present
            host: 127.0.0.1
            privs: '{{ item }}'
            type: database
            roles: '{{ student_user }}'
            login: '{{ student_user }}'
            password: '{{ student_password }}'
          with_items:
            - CREATE
            - CONNECT
            - TEMPORARY

    - name: Download Zabbix repo package
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb
        mode: '0640'

    - name: Install Zabbix repo
      apt:
        deb: /tmp/zabbix-release_6.4-1+ubuntu22.04_all.deb

    - name: install zabbix-server
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - zabbix-server-pgsql
        - zabbix-frontend-php
        - php8.1-pgsql
        - zabbix-apache-conf
        - zabbix-sql-scripts

    - name: Add DBPassword to Zabbix Server config
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        state: present
        regexp: '^# DBPassword=$'
        line: "DBPassword=ZabbixPasswd01"

    - name: Change Zabbix front port 1
      lineinfile:
        path: /etc/apache2/ports.conf
        state: present
        regexp: 'Listen 80'
        line: 'Listen 8080'

    - name: Change Zabbix front port 2
      lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: present
        regexp: ':80'
        line: '<VirtualHost *:8080>'

    - name: shell command on remote host
      shell:
        cmd: "zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix"
        #chdir: /home/andy/

    - name: Restart Zabbix
      systemd:
        name: "{{item}}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
       # - zabbix-agent
        - apache2
