---
# tasks file for zabbix_srv_install

- name: copy Docker Compose files
  copy:
    src: docker_zabbix_srv.yml
    dest: /home/andy/docker-compose.yml
    owner: andy
    group: docker

- name: shell command on remote host
  shell:
    cmd: "docker-compose -f docker-compose.yml up -d"
    chdir: /home/andy/
